### PR TITLE
feat: add option to extend methods

### PR DESCRIPTION
**Pull request by rek**
Re: https://github.com/koajs/cash/issues/58

note: if you are ok with merging this kind of thing, then i will update test, readme, and type package :)

### CODE REVIEW

**Comment by niftylettuce** [comment]
100% down to merge this!  would love if you could add a test and README!  I'll handle version bumping and the release in npm 😄

**Comment by rek** [comment]
Ok, how does this look now?

**Comment by rek** [comment]
note: to make this work really well, we also need to allow for a custom `hash`. Since on `POST` you also want to take into account the body (not just the url and params as in `GET`). But I will make new a PR for that later on.

**Comment by niftylettuce** [comment]
https://github.com/koajs/cash/releases/tag/v4.1.0

**Pull request merged**
